FROM python:3.9-slim

RUN apt-get update && apt-get install -y wget unzip

#RUN pip install torch==2.0.1+cpu torchvision>=0.15.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

# Создание директории для загрузки и распаковки файла
WORKDIR /app/stt/model/

# Загрузка файла по ссылке
RUN wget https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip

# Распаковка архива (в примере - zip)
RUN unzip vosk-model-small-ru-0.22.zip -d .

# Возвращение в основную директорию приложения
WORKDIR /app

# Установка зависимостей
COPY server/stt/vosk_req.txt .
RUN pip install --no-cache-dir -r vosk_req.txt

COPY server/stt/app_vosk.py .

CMD ["uvicorn", "app_vosk:app", "--host", "0.0.0.0", "--port", "8000"]
