version: "3.8"

services:
  stt:
    build:
      context: .
      dockerfile: /server/stt/Dockerfile_stt
    ports:
      - "8000:8000"

  translate:
    build:
      context: .
      dockerfile: /server/translate/Dockerfile_translate
    ports:
      - "8001:8001"
 
